# Generated by Django 5.2.7 on 2025-11-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_chapter_options_alter_chapter_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/covers/'),
        ),
    ]
