# Generated by Django 5.2.7 on 2025-11-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_chapter_visited',
            field=models.IntegerField(default=1),
        ),
    ]
