# Generated by Django 5.2.7 on 2025-11-06 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_last_chapter_visited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('protagonist', 'protagonist'), ('antagonist', 'antagonist'), ('supporting character', 'supporting character')], default='supporting character', max_length=32)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=64)),
                ('personality', models.TextField(blank=True, default='')),
                ('appearance', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('chapters_appeared', models.JSONField(blank=True, default=list)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='books.book')),
            ],
            options={
                'unique_together': {('book', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(blank=True, default='', max_length=255)),
                ('relation', models.CharField(max_length=128)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_relationships', to='books.book')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='books.character')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_relationships', to='books.character')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('book', 'source', 'relation', 'target', 'target_name'), name='unique_character_relationship')],
            },
        ),
    ]
