# Generated by Django 5.2.7 on 2025-11-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_character_characterrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
        migrations.DeleteModel(
            name='CharacterRelationship',
        ),
    ]
