# Generated by Django 5.2.7 on 2025-12-01 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_image_character_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('start_index', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('label', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='books.chapter')),
            ],
            options={
                'ordering': ['chapter', 'number'],
                'unique_together': {('chapter', 'number')},
            },
        ),
    ]
