# Generated by Django 5.2.7 on 2025-12-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
