# Generated by Django 5.2.7 on 2025-12-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_summary_book_synopsis_book_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='synopsis',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.AddField(
            model_name='book',
            name='inferred_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
