# Generated by Django 5.2.7 on 2025-12-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_book_synopsis_remove_book_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='relationships',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
